#!/bin/sh

# Source scripts in /etc/X11/xinit/xinitrc.d/
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

xhost +localhost

eval $(ssh-agent)

# lock screen fix for gnome 3.8 w/o gdm
# https://bbs.archlinux.org/viewtopic.php?pid=1265125#p1265125
gnome-screensaver &

exec gnome-session
#exec gnome-session-cinnamon
