#!/bin/sh

# Source scripts in /etc/X11/xinit/xinitrc.d/
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

xhost +localhost

# Caps Lock -> Ctrl
# Ctrl-Alt-Backspace kills X
# Remap navigation keys for Microsoft Sculpt
setxkbmap -option "terminate:ctrl_alt_bksp,ctrl:nocaps,sculpt:sculpt_navkeys"

# map Ctrl press-and-release to Escape
xcape -t 200 -e 'Control_L=Escape'

eval $(ssh-agent)

# lock screen fix for gnome 3.8 w/o gdm
# https://bbs.archlinux.org/viewtopic.php?pid=1265125#p1265125
gnome-screensaver &

redshift &

exec gnome-session
#exec gnome-session-cinnamon
