#!/bin/sh

export PATH=$HOME/.bin:$PATH
export PYTHONPATH=$HOME/.bin
export TEXINPUTS=".:$HOME/Documents/Repository/:"

export GTK_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"
export QT_IM_MODULE=fcitx

ibus-daemon -x -d
