#!/bin/bash

# watching while changing
# $ dconf watch /

# fix scrolling on touchpad
gsettings set org.gnome.settings-daemon.peripherals.touchpad scroll-method "edge-scrolling"

# free up Win key (Gnome 3.8)
gsettings set org.gnome.desktop.wm.keybindings switch-applications "['<Alt>Tab', '<Alt>Tab']"
gsettings set org.gnome.desktop.wm.keybindings switch-group "['<Alt>Above_Tab', '<Alt>Above_Tab']"
gsettings set org.gnome.desktop.wm.keybindings minimize "['']"
gsettings set org.gnome.shell.keybindings focus-active-notification "['']"
gsettings set org.gnome.shell.keybindings toggle-message-tray "['']"

# mime association
xdg-mime default zathura.desktop application/pdf

# Terminal
gsettings set org.gnome.Terminal.Legacy.Settings menu-accelerator-enabled false
gsettings set org.gnome.Terminal.Legacy.Settings default-show-menubar false

# Desktop
gsettings set org.gnome.shell always-show-log-out true
gsettings set org.gnome.nautilus.desktop home-icon-visible false
gsettings set org.gnome.nautilus.desktop trash-icon-visible false
gsettings set org.gnome.desktop.background show-desktop-icons true
gsettings set org.gnome.desktop.interface clock-show-date true
gsettings set org.gnome.desktop.privacy show-full-name-in-top-bar false

# Nautilus
gsettings set org.gnome.nautilus.preferences sort-directories-first true
gsettings set org.gnome.nautilus.icon-view default-zoom-level 'small'
gsettings set org.gnome.nautilus.list-view default-zoom-level 'small'

# Power
gsettings set org.gnome.settings-daemon.plugins.power button-power 'interactive'
gsettings set org.gnome.settings-daemon.plugins.power lid-close-ac-action 'nothing'

# Caps Lock -> Ctrl
# Ctrl-Alt-Backspace kills X
gsettings set org.gnome.desktop.input-sources xkb-options "['caps:ctrl_modifier', 'terminate:ctrl_alt_bksp']"

## Cinnamon
#gsettings set org.nemo.desktop computer-icon-visible false
#gsettings set org.nemo.desktop home-icon-visible false
#gsettings set org.nemo.desktop trash-icon-visible false
#gsettings set org.cinnamon.muffin overlay-key ''
#gsettings set org.cinnamon desktop-effects false
#gsettings set org.cinnamon desktop-layout 'flipped'

# disable animations
gsettings set org.gnome.desktop.interface enable-animations false

# Windows
gsettings set org.gnome.shell.overrides button-layout ':minimize,maximize,close'
gsettings set org.gnome.desktop.wm.keybindings show-desktop "['<Super>d']"
gsettings set org.gnome.desktop.wm.keybindings panel-main-menu "['']"
gsettings set org.gnome.desktop.wm.keybindings toggle-maximized "['<Alt>F1']"
gsettings set org.gnome.desktop.wm.preferences action-middle-click-titlebar 'none'

# shellshape tiling
SD=~/.local/share/gnome-shell/extensions/shellshape@gfxmonk.net/data/glib-2.0/schemas
gsettings --schemadir $SD set org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings adjust-splits-to-fit "['<Mod4>p']"
gsettings --schemadir $SD set org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings set-layout-tiled-vertical "['<Mod4>z']"
gsettings --schemadir $SD set org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings set-layout-floating "['<Mod4>x']"
gsettings --schemadir $SD set org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings set-layout-tiled-horizontal "[]"
gsettings --schemadir $SD set org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings set-layout-fullscreen "[]"
gsettings --schemadir $SD set org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings set-layout-floating "[]"
gsettings --schemadir $SD set org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings rotate-current-window-reverse "[]"
gsettings --schemadir $SD set org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings rotate-current-window "[]"
gsettings --schemadir $SD set org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings swap-current-window-with-main "[]"
gsettings --schemadir $SD set org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings switch-workspace-down "[]"
gsettings --schemadir $SD set org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings switch-workspace-up "[]"
gsettings --schemadir $SD set org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings move-window-workspace-down "[]"
gsettings --schemadir $SD set org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings move-window-workspace-up "[]"
gsettings --schemadir $SD set org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings focus-main-window "[]"
gsettings --schemadir $SD set org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings next-window "[]"
gsettings --schemadir $SD set org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings prev-window "[]"
gsettings --schemadir $SD set org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings increase-size "[]"
gsettings --schemadir $SD set org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings decrease-size "[]"
gsettings --schemadir $SD set org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings increase-main-size "[]"
gsettings --schemadir $SD set org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings decrease-main-size "[]"
gsettings --schemadir $SD set org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings increase-minor-size "[]"
gsettings --schemadir $SD set org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings decrease-minor-size "[]"
gsettings --schemadir $SD set org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings increase-minor-split "[]"
gsettings --schemadir $SD set org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings decrease-minor-split "[]"
gsettings --schemadir $SD set org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings increase-main-split "[]"
gsettings --schemadir $SD set org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings decrease-main-split "[]"
gsettings --schemadir $SD set org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings minimize-window "[]"
gsettings --schemadir $SD set org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings toggle-maximize "[]"
gsettings --schemadir $SD set org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings unminimize-last-window "[]"

# Workspace
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-1 "['<Super>h']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-2 "['<Super>j']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-3 "['<Super>k']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-4 "['<Super>l']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-5 "['<Super>semicolon']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-6 "['<Super>apostrophe']"

# screenshot
gsettings set org.gnome.settings-daemon.plugins.media-keys screenshot '<Super>Print'

# lock screen
gsettings set org.gnome.settings-daemon.plugins.media-keys screensaver '<Primary><Alt>l'

# Launchers
gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/']"
# help on gsettings: http://blogs.gnome.org/fmuellner/2011/11/22/gnome-shell-gsettings-and-keybindings/comment-page-1/#comment-128
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding '<Super>grave'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command 'gnome-terminal'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name 'Gnome Terminal'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ binding '<Super>e'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ command 'nautilus'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ name 'Nautilus'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ binding '<Super>c'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ command 'gnome-calculator'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ name 'Calculator'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/ binding '<Super>v'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/ command 'gvim'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/ name 'GVim'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/ binding '<Super>n'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/ command 'gedit'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/ name 'Gedit'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/ binding '<Super>F1'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/ command 'latex-to-unicode.sh'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/ name 'LaTeX to Unicode'
