#!/usr/bin/env python

from pandocfilters import toJSONFilter, Math


def eqref(key, value, fmt, meta):
    r"""
    Wrap \ref and \eqref in Math().
    """
    if fmt != 'html':
        return None

    if key == 'RawInline' and value[0] == 'tex':
        if value[1].startswith(r'\ref') or value[1].startswith(r'\eqref'):
            return Math(dict(t='InlineMath'), value[1])

    return None


if __name__ == '__main__':
    toJSONFilter(eqref)
