#!/usr/bin/env python

import os
from pandocfilters import toJSONFilter


def log(key, value, fmt, meta):
    """
    Logging helper as a filter.
    """
    with open(os.environ.get('PANDOC_LOG', 'z.log'), 'a') as f:
        f.write(f'{key = !r}\n')
        f.write(f'{value = !r}\n')
        f.write(f'{fmt = !r}\n')
        f.write(f'{meta = !r}\n')
        f.write('\n')

    return None


if __name__ == "__main__":
    toJSONFilter(log)
