#!/bin/sh

export PATH=$HOME/sandbox/diagham/build/src/Programs:$HOME/sandbox/diagham/build/FQHE/src/Programs/FQHEOnSphere:$HOME/sandbox/diagham/build/FQHE/src/Programs/FQHEOnTorus:$HOME/sandbox/diagham/build/FQHE/src/Programs/FQHETopInsulator:$PATH
