#!/usr/bin/env python

import os
import sys


def find_venv(filename):
    """
    Find the ".venv/bin/activate" script in a parent directory.
    """
    path = os.path.realpath(os.path.abspath(filename))
    while path != '/':
        activate = os.path.join(path, '.venv/bin/activate')
        if os.path.isfile(activate):
            return activate
        path = os.path.dirname(path)
    return '/dev/null'


if __name__ == '__main__':
    print(find_venv(sys.argv[1]))
