#!/usr/bin/env python2

import os
import os.path as op
import sys

def find_venv(filename):
    """find a venv activate script in a parent directory"""
    path = op.realpath(op.abspath(filename))
    while path != '/':
        activate = op.join(path, '.venv/bin/activate')
        if op.isfile(activate):
            return activate
        path = op.dirname(path)
    return '/dev/null'

if __name__ == '__main__':
    print find_venv(sys.argv[1])
