#!/bin/bash

# Mark the previously focused window with _prev.
# Adapted from https://redd.it/4d4luc

id_prev=

xprop -root -spy _NET_ACTIVE_WINDOW |
    while read line
    do
        [[ -z "$id_prev" ]] || i3-msg "[id=$id_prev] mark --add _prev"
        id_prev=$(echo "$line" | awk -F' ' '{printf $NF}')
    done
