#!/usr/bin/env python

# Inline \input{...} files for LaTeX source.

import re
import sys


def main(input_filename, output_filename):
    pattern = re.compile(r'^\s*\\input{(?P<include_filename>.*)}\s*$')
    output_lines = []
    with open(input_filename) as f:
        for line in f:
            if m := pattern.match(line):
                with open(m.group('include_filename')) as i:
                    output_lines.append(i.read() + '\n')
            else:
                output_lines.append(line)

    with open(output_filename, 'w') as f:
        f.write(''.join(output_lines))


if __name__ == '__main__':
    main(*sys.argv[1:])
