#!/usr/bin/python2

def joinpdf(filenames, output):
    """join pdf files"""
    from sys import exit

    from os.path import isfile
    if isfile(output):
        print 'output "%s" already exits!' % output
        exit(1)

    command = r'gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile="%s" "%s"' % (output, r'" "'.join(filenames))
    print command

    from utils import execute
    execute(command, choke=True)

if __name__ == '__main__':
    from sys import argv, exit

    if len(argv) < 4:
        print "Usage: joinpdf 1.pdf 2.pdf 3.pdf ... output.pdf"
        exit(1)

    joinpdf(argv[1:-1], argv[-1])

