#!/usr/bin/python2

from argh import arg
@arg('-f', action='store_true', help='overwrite output')
@arg('filenames', type=str, nargs='+', metavar='input.pdf', help='input pdf filenames')
@arg('output', type=str, metavar='output.pdf', help='output pdf filename')
def joinpdf(f, filenames, output):
    """join pdf files"""

    if not f:
        from sys import exit
        from os.path import isfile
        if isfile(output):
            print 'output "%s" already exits!' % output
            exit(1)

    command = r'gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -dAutoRotatePages=/None '
    command += r'-sOutputFile="%s" "%s"' % (output, '" "'.join(filenames))
    print command

    from utils import execute
    execute(command, choke=True)

if __name__ == '__main__':
    from argh.helpers import ArghParser
    parser = ArghParser()
    parser.set_default_command(joinpdf)
    parser.dispatch()
