#!/usr/bin/python3

import argh
import os
import subprocess
import sys


def execute(command, choke=False):
    """
    Execute command in current directory, and optionally choke on non-zero
    return code.
    """
    p = subprocess.Popen([command], shell=True, stdout=subprocess.PIPE,
                         stderr=subprocess.PIPE)
    stdout, stderr = p.communicate()

    if choke and p.returncode != 0:
        if len(stdout) > 0:
            print(stdout, end='')
        if len(stderr) > 0:
            print(stderr, end='')

        sys.exit(p.returncode)

    return stdout, stderr, p.returncode


@argh.arg('filenames', type=str, nargs='+', metavar='input.pdf',
          help='Input pdf filenames.')
@argh.arg('output', type=str, metavar='output.pdf',
          help='Output pdf filename.')
@argh.arg('-f', help='Whether to overwrite output.')
def joinpdf(filenames, output, f=False):
    """
    Join pdf files.
    """
    if not f and os.path.isfile(output):
        print('output "%s" already exits!' % output)
        sys.exit(1)

    quoted_inputs = ' '.join(f'"{filename}"' for filename in filenames)
    command = (
        f'gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -dAutoRotatePages=/None '
        f'-sOutputFile="{output}" {quoted_inputs}'
    )
    print(command)
    execute(command, choke=True)


if __name__ == '__main__':
    argh.dispatch_command(joinpdf)
