#!/usr/bin/python2

from argh import arg

@arg('filename', type=str, help='.tex filename')
@arg('--temp', type=str, help='path for temporary file', default='.tmpTeX')
@arg('--latex', action='store_true', help='use latex rather than pdflatex', default=False)
def run(filename, temp, latex):
    """compile LaTeX without littering"""
    filename = find_master(filename)

    from utils import execute, mkdir
    mkdir(temp)
    execute('cp *.bst %s/' % temp)
    execute('cp *.bib %s/' % temp)

    command = r'rubber --into .tmpTeX -%sfsq "%s"' % ('p' if latex else 'd', filename)
    execute(command, choke=True)

    from os.path import join, basename, splitext
    name = basename(splitext(filename)[0])
    if latex:
        execute('dvipdf %s %s' % (join(temp, name + '.dvi'), name + '.pdf'), choke=True)
    else:
        execute('cp "%s" .' % join(temp, name + '.pdf'), choke=True)

def find_master(filename):
    """find the master .tex file"""
    with open(filename) as f:
        line = f.readline().rstrip(' \t\r\n')
    if line[0:8] == r'%MASTER=':
        return line[8:]
    else:
        return filename

if __name__ == '__main__':
    from argh.helpers import ArghParser
    parser = ArghParser()
    parser.set_default_command(run)
    parser.dispatch()
