#!/bin/bash

set -e

# search for multiple words: https://stackoverflow.com/a/44754369
PATTERN="(?s)"
for q in "$@"; do
    q=${q/ /\\s+}  # replace ' ' by \s+
    PATTERN+="(?=.*$q)"
done

# split by '\0': https://unix.stackexchange.com/a/204905
FILES=()
while IFS= read -r -d '' file; do
    FILES+=("$file")
done < <(ag -0 -l -m1 --silent --nocolor --smart-case "$PATTERN")

printf '  %s\n' "${FILES[@]}"
#read -p "Open? " -n 1 -r
#
## E173 hack: https://redd.it/1vqj4l
#gvim -c "bprev" -c "bnext" "${FILES[@]}" &>/dev/null

# xargs and vim: https://superuser.com/a/427881
#ag -0 -l --nocolor --smart-case "$PATTERN" | xargs -r -0 bash -c '</dev/tty vim -c "bprev" -c "bnext" "$@"' ignoreme
