#!/usr/bin/env python2
# -*- coding: utf8 -*-

def convert(filename, dest='eps'):
    """convert pdf → ps → eps"""
    from utils import mkdir
    mkdir(dest)

    from os.path import abspath, join, basename, splitext
    base = splitext(basename(filename))[0]
    ps = join(dest, base + '.ps')
    eps = join(dest, base + '.eps')

    from utils import execute
    execute('pdftops-cairo "%s" "%s"' % (filename, ps), choke=True)
    execute('ps2eps -f "%s"' % ps, choke=True)
    execute('rm "%s"' % ps, choke=True)

if __name__ == '__main__':
    from sys import argv
    for filename in argv[1:]:
        convert(filename)
