#!/bin/bash

# Taking snapshot of Arch Linux Repository, adapted from http://lmbrt.com/a/230

# This script expects in $HOME/mirror a symlink 'archlinux' pointing to an existing repo folder
# To get started, just create an empty folder and link it

set -e

cd $HOME/mirror
mkdir -p log

HOST="http://arch.mirror.constant.com"
#SIZERANGE="--size-range=0-100000000" # 100M
SIZERANGE=""
TIMESTAMP=`date +"%Y%m%d"`
LOGSTAMP=`date +"%Y%m%d-%H%M%S"`
CURRENT=`readlink archlinux`
echo $TIMESTAMP
echo $CURRENT

[[ $CURRENT == $TIMESTAMP ]] || cp -al $CURRENT $TIMESTAMP

trickle -sd 5000 lftp $HOST -e "
lcd $TIMESTAMP
mirror $SIZERANGE --delete -n -P5 --dereference core/os/x86_64 core/os/x86_64 --log=../log/$LOGSTAMP-core.log
mirror $SIZERANGE --delete -n -P5 --dereference extra/os/x86_64 extra/os/x86_64 --log=../log/$LOGSTAMP-extra.log
mirror $SIZERANGE --delete -n -P5 --dereference multilib/os/x86_64 multilib/os/x86_64 --log=../log/$LOGSTAMP-multilib.log
mirror $SIZERANGE --delete -n -P5 --dereference community/os/x86_64 community/os/x86_64 --log=../log/$LOGSTAMP-community.log
bye
"
# seems that using --loop with --delete causes
# "Retrying mirror...\n rm: Access failed: abc.tar.xz: No such file or directory"
# error for all the files removed in the first iteration

rm archlinux
ln -s $TIMESTAMP archlinux
