#!/bin/bash

# start Vivaldi in a "throwaway" profile (duplicated from Default)

set -e

OLD=~/.config/vivaldi
NEW=/tmp/vivaldi-`pwgen 6 1`

OLDD=$OLD/Default
NEWD=$NEW/Default

mkdir -p $NEWD

cp $OLD/"First Run" $NEW/
cp $OLDD/Bookmarks $NEWD/
cp $OLDD/Favicons $NEWD/
cp $OLDD/Preferences $NEWD/

cp -r $OLDD/Extensions $NEWD/

cp -r $OLDD/"Local App Settings" $NEWD/ # theme
cp -r $OLDD/"Local Extension Settings" $NEWD/ # uBlock
cp -r $OLDD/"Local Storage" $NEWD/ # pinboard

vivaldi-stable --user-data-dir=$NEW $1
rm -rf "$NEW"
