#!/bin/bash

orientation=$(echo "portrait
landscape" | rofi -dmenu -p "Orientation: ")

export ICAROOT=/opt/Citrix/ICAClient

echo +$orientation+lol

if [[ "$orientation" == "landscape" ]]; then
    i3-msg 'workspace "L"'
    ${ICAROOT}/wfica -geometry 2560x1417 -file "$1"
else
    i3-msg 'workspace "R"'
    ${ICAROOT}/wfica -geometry 1440x2537 -file "$1"
fi
